name: Update THM Badge

on:
  schedule:
    - cron: '0 */6 * * *'   # cada 6 horas
  workflow_dispatch:         # permite ejecutarlo manualmente

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download THM badge
        run: |
          curl -L "https://tryhackme.com/api/v2/badges/public-profile?userPublicId=3084093" -o assets/badge/thm-badge.svg

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/badge/thm-badge.svg
          git commit -m "Auto-update THM badge" || echo "No changes to commit"

      - name: Push
        run: |
          git push
