name: Update THM Badge

on:
  schedule:
    - cron: '0 */6 * * *'   # cada 6 horas
  workflow_dispatch:         # para lanzarlo a mano

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure badge dir exists
        run: mkdir -p assets/badge

      - name: Download THM badge
        run: |
          curl -L "https://tryhackme.com/api/v2/badges/public-profile?userPublicId=3084093" \
            -o assets/badge/thm-badge.svg

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/badge/thm-badge.svg
          git commit -m "Auto-update THM badge" || echo "No changes to commit"
          git push

